version: "3"
services:
    postgres:
        image: postgres:12
        restart: unless-stopped
        env_file:
            - .env.development
    sushii-2:
        image: docker.pkg.github.com/drklee3/sushii-2/sushii-2:master
        restart: unless-stopped
        volumes:
            - ./sushii:/config
