version: "3.8"
services:
    postgres:
        ports:
            - "5432:5432"
    sushii:
        build:
            dockerfile: ./sushii-2/Dockerfile
            context: .
    sushii-api:
        build:
            dockerfile: ./sushii-api/Dockerfile
            context: .
        ports:
            - "8080:8080"
