[package]
name = "sushii-model"
version = "0.1.0"
authors = ["drklee3 <derrick@dlee.dev>"]
edition = "2018"

[dependencies]
chrono = "0.4"
dashmap = "4.0.0-rc6"
futures = "0.3"
humantime = "2.0"
lazy_static = "1.4"
num-format = "0.4"
num-traits = "0.2.14"
rand = "0.7.3"
rand_distr = "0.3.0"
regex = "1.3"
serde = "1.0.114"
serde_json = "1.0.57"
tracing = "0.1"

[dependencies.metrics]
# version = "0.13.0-alpha.11"
git = "https://github.com/metrics-rs/metrics.git"
branch = "main"

[dependencies.tokio]
version = "0.2"
features = ["macros", "rt-core", "time", "signal"]

[dependencies.sqlx]
version = "0.4.1"
default-features = false
features = [ "runtime-tokio-rustls", "macros", "postgres", "json", "chrono", "offline", "migrate", "decimal" ]

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "current"
# path = "../serenity"
# version = "0.9.2"
