[package]
name = "sushii-2"
version = "0.1.14"
authors = ["drklee3 <derrick@dlee.dev>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
chrono = "0.4"
dashmap = "4.0.0-rc6"
dotenv = "0.15"
futures = "0.3"
humantime = "2.0"
hyper = "0.13"
lazy_static = "1.4"
num_cpus = "1.13"
num-format = "0.4"
num-traits = "0.2.14"
rand = "0.7.3"
rand_distr = "0.3.0"
regex = "1.3"
reqwest = { version = "0.10", features = [ "json" ] }
sentry = {version = "0.21", default-features= false, features = ["backtrace", "contexts", "panic", "reqwest", "rustls"]}
serde = "1.0.114"
serde_json = "1.0.57"
serde_yaml = "0.8.14"
tracing = "0.1"
tracing-subscriber = "0.2"

[dependencies.sushii-model]
path = "../sushii-model"

[dependencies.metrics]
# version = "0.13.0-alpha.11"
git = "https://github.com/metrics-rs/metrics.git"
branch = "main"

[dependencies.metrics-exporter-prometheus]
# version = "0.1.0-alpha.10"
git = "https://github.com/metrics-rs/metrics.git"
branch = "main"

[dependencies.metrics-util]
git = "https://github.com/metrics-rs/metrics.git"
branch = "main"

[dependencies.lastfm-rs]
git = "https://github.com/KamranMackey/lastfm-rs"
branch = "main"
# path = "../lastfm-rs"

[dependencies.tokio]
version = "0.2"
features = ["macros", "rt-core", "time", "signal"]

[dependencies.sqlx]
version = "0.4.1"
default-features = false
features = [ "runtime-tokio-rustls", "macros", "postgres", "json", "chrono", "offline", "migrate", "decimal" ]

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "current"
# path = "../serenity"
# version = "0.9.2"
features = ["default", "collector"]
