[package]
name = "sushii-2"
version = "0.2.1"
authors = ["drklee3 <derrick@dlee.dev>"]
edition = "2018"
build = "build.rs"

[dependencies]
async-trait = "0.1"
chrono = "0.4"
dashmap = "4.0.0-rc6"
dotenv = "0.15"
futures = "0.3"
humantime = "2.0"
hyper = "0.13"
lazy_static = "1.4"
metrics = "=0.13.0-alpha.13"
metrics-exporter-prometheus = "=0.1.0-alpha.12"
metrics-util = "=0.4.0-alpha.10"
num_cpus = "1.13"
num-format = "0.4"
num-traits = "0.2.14"
rand = "0.7.3"
rand_distr = "0.3.0"
regex = "1.3"
reqwest = { version = "0.10", features = [ "json" ] }
sentry = {version = "0.21", default-features= false, features = ["backtrace", "contexts", "panic", "reqwest", "rustls"]}
serde = "1.0.114"
serde_json = "1.0.57"
serde_yaml = "0.8.14"
tracing = "0.1"
tracing-subscriber = "0.2"
heim = { version = "0.1.0-rc.1", features = ["cpu", "process", "memory"]}

[dependencies.sushii-model]
path = "../sushii-model"

[dependencies.sushii-feeds]
path = "../sushii-feeds"
default-features = false
features = []

[dependencies.vlive]
git = "https://github.com/drklee3/vlive-rs"
rev = "04e13d0ca81bc420709f283604465491ed8671e4"

[dependencies.lastfm-rs]
git = "https://github.com/sushiibot/lastfm-rs"
rev = "a5d58142c3172febd3e83d5ad9824ce00cf9834f"
# path = "../lastfm-rs"

[dependencies.tokio]
version = "0.2"
features = ["macros", "rt-threaded", "time", "signal"]

[dependencies.sqlx]
version = "0.4.1"
default-features = false
features = [ "runtime-tokio-rustls", "macros", "postgres", "json", "chrono", "offline", "migrate", "decimal" ]

[dependencies.serenity]
# git = "https://github.com/serenity-rs/serenity"
# rev = "0b1fc2737efebde01f6f3b781bcdfc83a30e908e"
version = "0.10.2"
default-features = false
features = ["default_tokio_0_2", "collector"]

[build-dependencies.vergen]
version = "4.0.3"
default-features = false
features = ["build", "rustc"]
