name: CI

on: [push, pull_request]

jobs:
    test-packages:
        name: Test ${{ matrix.package }} ${{ matrix.args }}
        strategy:
            fail-fast: false
            matrix:
                package:
                    - sushii-2
                    - sushii-api
                    - sushii-model
                include:
                    - package: sushii-api
                      args: --all-features
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Select toolchain
              id: toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true

            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-test-rustc-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

            - name: Build ${{ matrix.package }}
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --package ${{ matrix.package }} ${{ matrix.args }}

            - name: Test ${{ matrix.package }}
              uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: --package ${{ matrix.package }} ${{ matrix.args }}
