name: CI

on: [push, pull_request]

jobs:
    build:
        continue-on-error: ${{ matrix.toolchain == 'nightly' }}
        strategy:
            matrix:
                toolchain:
                    - stable
                    - beta
                    - nightly
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Select toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.toolchain }}
                  override: true

            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Build sushii
              uses: actions-rs/cargo@v1
              with:
                  command: build

            - name: Test sushii
              uses: actions-rs/cargo@v1
              with:
                  command: test

            - name: Install sqlx-cli
              run: cargo install --version=0.1.0-beta.1 sqlx-cli --no-default-features --features postgres

            - name: Check sqlx queries
              run: cargo sqlx prepare --check

            - name: Upload artifacts
              if: matrix.toolchain == 'stable'
              uses: actions/checkout@v2
              with:
                  name: sushii2-${{github.run_id}}
                  path: ./target/release/sushii-2
