name: Docker

on:
    push:
        tags:
            - v*

env:
    IMAGE_NAME: sushii-2

jobs:
    push:
        # Ensure test job passes before pushing image.
        # needs: test
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - uses: actions/checkout@v2

            - name: Set Docker Tags
              id: set_tags
              run: |
                  # Strip git ref prefix from version
                  TAGS=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

                  # Strip "v" prefix from tag name
                  [[ "${{ github.ref }}" == "refs/tags/"* ]] && TAGS=$(echo $TAGS | sed -e 's/^v//')

                  # Add stable and latest tag to tagged versions
                  [ "$TAGS" != "master" ] && TAGS=${TAGS},stable,latest

                  echo ::set-output name=tags::${TAGS}
                  echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
                  echo "Docker image tags: $TAGS"
                  echo ${{ steps.set_tags.outputs.tags }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.CR_PAT }}

            - name: Build and push image to GitHub Packages
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  pull: true
                  push: true
                  tags: ${{ steps.set_tags.outputs.tags }}
                  cache-from: type=registry,ref=drklee3/sushii-2:latest
                  cache-to: type=inline
                  labels: |
                      org.opencontainers.image.source=${{ github.event.repository.html_url }}
                      org.opencontainers.image.created=${{ steps.set_tags.outputs.created }}
                      org.opencontainers.image.revision=${{ github.sha }}
